# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: formain

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install pandas
        pip list
    - name: Set up Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install dependencies
      run: |
        npm install --production --no-audit
        npm list --depth=0
    - name: run app
      run: |
        mkdir -p result
        python ./util/pdnormalize.py
        python ./util/slicebatch.py
        node formain.js > ./result/nbatch.log
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output artifacts
        path: |
          ./result/nbatch.log