name: node-batch
on:
  push:
    branches: [main]

jobs:
  Build:
    # Specifies that the build will run on the latest Ubuntu version
    runs-on: ubuntu-22.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Sets up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Caches Python dependencies to speed up builds
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      # Installs Python dependencies from requirements.txt if it exists
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip list

      # Sets up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Installs Node.js dependencies and some required system packages
      - name: Install Node.js dependencies
        run: |
          npm ci --omit=optional --no-audit
          npm list --depth=0

      # Runs a series of npm scripts defined in package.json
      - name: run app
        run: |
          npm run cooking
          npm run main+batch
          npm run plot-batch

      # Archives the specified artifacts (logs and images) from the workflow
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output-artifacts
          path: |
            ./result/output1.log
            ./result/plot-batch.png
