on:
  push:
    branches: [master]

jobs:
  setup_dependencies:
    runs-on: ubuntu-latest
    outputs:
      cache-key-py: ${{ steps.cache-py.outputs.cache-key }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Python dependencies
        id: cache-py
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          python -m pip install --upgrade pip setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  main_job:
    needs: setup_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Python cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ needs.setup_dependencies.outputs.cache-key-py }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip list

      - name: Set up Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"

      - name: Install Node.js dependencies
        run: |
          npm ci --no-audit
          npm list --depth=0
          sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config

      - name: run npm script
        run: |
          npm run cooking
          npm run main+batch

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: main-artifacts
          path: ./result/nbatch.log

  sakata_job:
    needs: setup_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use cached dependencies
      - name: Use Python cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ needs.setup_dependencies.outputs.cache-key-py }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip list

      - name: Set up Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"

      - name: Install Node.js dependencies
        run: |
          npm ci --no-audit
          npm list --depth=0
          sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config

      - name: run sakata+batch
        run: |
          npm run cooking
          npm run sakata+batch

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sakata-artifacts
          path: ./result/sakata-batch.log

  merge_artifacts:
    needs: [main_job, sakata_job]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Confirm the directory and move files
        run: ls -R
      - run: mv ./main-artifacts/nbatch.log ./result/nbatch.log
      - run: mv ./sakata-artifacts/sakata-batch.log ./result/sakata-batch.log

      - name: Use Python cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ needs.setup_dependencies.outputs.cache-key-py }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install matplotlib

      - run: npm run plot-multi

      - name: Archive all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: result-artifacts
          path: |
            ./result/nbatch.log
            ./result/sakata-batch.log
            ./result/plot-multi.png
