name: parallel-jobs
on:
  push:
    branches: [master]

jobs:
  setup-build:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.idcache-key.outputs.key }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Generate cache key for Python dependencies
        id: idcache-key
        run: echo "key=${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}" >> $GITHUB_OUTPUT

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set up Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci --omit=optional --no-audit

  main_job:
    needs: setup-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Use Python cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ needs.setup-build.outputs.cache-key }}

      - name: Run npm script
        run: |
          npm run cooking
          npm run main+batch

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: main-artifacts
          path: ./result/main-batch.log

  sakata_job:
    needs: setup-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Use Python cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ needs.setup-build.outputs.cache-key }}

      - name: Install additional dependencies for sakata+batch
        run: sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config

      - name: Run sakata+batch
        run: |
          npm run cooking
          npm run sakata+batch

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sakata-artifacts
          path: ./result/sakata-batch.log

  merge_artifacts:
    needs: [main_job, sakata_job]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          name: main-artifacts

      - uses: actions/download-artifact@v4
        with:
          name: sakata-artifacts

      - name: Confirm the directory and move files
        run: |
          ls -R
          mv ./main-artifacts/main-batch.log ./result/main-batch.log
          mv ./sakata-artifacts/sakata-batch.log ./result/sakata-batch.log

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Use Python cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ needs.setup-build.outputs.cache-key }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install matplotlib numpy

      - name: Run plot-multi
        run: npm run plot-multi

      - name: Archive all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output-artifacts
          path: |
            ./result/main-batch.log
            ./result/sakata-batch.log
            ./result/plot-multi.png
