name: parallel

on:
  push:
    branches: [master]

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10 and dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          python -m pip install --upgrade pip setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip list

      - name: Set up Node.js 16 and dependencies
        uses: actions/setup-node@v4
        with:
          node-version: "16"
      - run: |
          npm ci --no-audit
          npm list --depth=0

      - name: run npm script
        run: |
          npm run cooking
          npm run main+batch

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: main-artifacts
          path: |
            ./result/nbatch.log

  sakata_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip list

      - name: Set up Node.js 16 and dependencies
        uses: actions/setup-node@v4
        with:
          node-version: "16"
      - run: |
          npm ci --no-audit
          npm list --depth=0
          sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config

      - name: run sakata+batch
        run: |
          npm run cooking
          npm run sakata+batch

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sakata-artifacts
          path: |
            ./result/sakata-batch.log

  merge_artifacts:
    needs: [main_job, sakata_job]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10 and dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          python -m pip install --upgrade pip setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip list

      - run: npm run plot-multi

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: List all downloaded files
        run: ls -R
      - name: Archive all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-artifacts
          path: |
            ./main-artifacts/nbatch.log
            ./sakata-artifacts/sakata-batch.log
            ./result/plot-multi.png
