# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: python loop

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip list
    - name: run app
      run: |
        python pdnormalize.py
        python slicebatch.py
        mkdir result
        python forpyndevice.py > ./result/pbatch.log
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: output artifacts
        path: |
          ./result