name: Manual Trigger Workflow
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        
    - name: Set timezone to Japan Standard Time (JST)
      run: sudo timedatectl set-timezone Asia/Tokyo

    - name: Display current time
      run: date
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-w.txt
        pip list
    - name: run app
      run: npm run getdata

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: output-artifacts
        path: |
          ./csv/hdatexyt.csv
