name: tensorflow
on:
  workflow_dispatch:

jobs:
  Build:
    # Specifies that the build will run on the latest Ubuntu version
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Sets up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Caches Python dependencies to speed up builds
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-t.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      # Installs Python dependencies from requirements.txt if it exists
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements-t.txt
          pip list

      # Runs a series of npm scripts defined in package.json
      - name: run app
        run: |
          python ./utils/slicebatch.py
          python ./src/python/sakata3b.py > ./result/output3.log
          python ./src/python/plot-batch.py ./result/output3.log

      # Archives the specified artifacts (logs and images) from the workflow
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output-artifacts
          path: |
            ./result/output3.log
            ./result/plot-output3.png
