name: test-sakata
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci --no-audit
          npm list --depth=0
          sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config
          npm run sakata

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output artifacts
          path: |
            ./result/sakata.txt
