on: [push]
jobs:
  setup-build:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.idcache-keys.outputs.key }}
    steps:
      - uses: actions/checkout@v2

      - name: Generate cache key for Python dependencies
        id: idcache-keys
        run: echo "::set-output name=key::${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"

  build:
    needs: setup-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ needs.setup-build.outputs.cache-key }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
