name: test-id
on: [push]

jobs:
  setup-build:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.idcache-key.outputs.key }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate cache key for Python dependencies
        id: idcache-key
        run: echo "key=${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}" >> $GITHUB_OUTPUT

  build:
    needs: setup-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            !~/.cache/pip/log
          key: ${{ needs.setup-build.outputs.cache-key }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
